"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createStorage = exports.ChannelStorage = exports.createRegistry = exports.ChannelRegistry = exports.isUserAllowed = exports.matchesFilterPatterns = exports.isValidChannelType = exports.isValidChannelId = exports.assertValidChannelConfig = exports.validateChannelConfig = exports.CURRENT_VERSION = exports.ChannelAlreadyExistsError = exports.ChannelValidationError = exports.ChannelNotFoundError = exports.ChannelError = exports.ConnectionTestResultSchema = exports.ValidationResultSchema = exports.ChannelsConfigSchema = exports.ChannelConfigSchema = exports.ConnectionStatusSchema = exports.WebhookSettingsSchema = exports.ChannelSettingsSchema = exports.WebhookConfigSchema = exports.WebhookRetryPolicySchema = exports.WebhookAuthSchema = exports.WhatsAppConfigSchema = exports.EmailConfigSchema = exports.EmailServerConfigSchema = exports.SlackConfigSchema = exports.DiscordConfigSchema = exports.TelegramConfigSchema = exports.RateLimitConfigSchema = exports.ChannelType = void 0;
var types_js_1 = require("./types.js");
Object.defineProperty(exports, "ChannelType", { enumerable: true, get: function () { return types_js_1.ChannelType; } });
Object.defineProperty(exports, "RateLimitConfigSchema", { enumerable: true, get: function () { return types_js_1.RateLimitConfigSchema; } });
Object.defineProperty(exports, "TelegramConfigSchema", { enumerable: true, get: function () { return types_js_1.TelegramConfigSchema; } });
Object.defineProperty(exports, "DiscordConfigSchema", { enumerable: true, get: function () { return types_js_1.DiscordConfigSchema; } });
Object.defineProperty(exports, "SlackConfigSchema", { enumerable: true, get: function () { return types_js_1.SlackConfigSchema; } });
Object.defineProperty(exports, "EmailServerConfigSchema", { enumerable: true, get: function () { return types_js_1.EmailServerConfigSchema; } });
Object.defineProperty(exports, "EmailConfigSchema", { enumerable: true, get: function () { return types_js_1.EmailConfigSchema; } });
Object.defineProperty(exports, "WhatsAppConfigSchema", { enumerable: true, get: function () { return types_js_1.WhatsAppConfigSchema; } });
Object.defineProperty(exports, "WebhookAuthSchema", { enumerable: true, get: function () { return types_js_1.WebhookAuthSchema; } });
Object.defineProperty(exports, "WebhookRetryPolicySchema", { enumerable: true, get: function () { return types_js_1.WebhookRetryPolicySchema; } });
Object.defineProperty(exports, "WebhookConfigSchema", { enumerable: true, get: function () { return types_js_1.WebhookConfigSchema; } });
Object.defineProperty(exports, "ChannelSettingsSchema", { enumerable: true, get: function () { return types_js_1.ChannelSettingsSchema; } });
Object.defineProperty(exports, "WebhookSettingsSchema", { enumerable: true, get: function () { return types_js_1.WebhookSettingsSchema; } });
Object.defineProperty(exports, "ConnectionStatusSchema", { enumerable: true, get: function () { return types_js_1.ConnectionStatusSchema; } });
Object.defineProperty(exports, "ChannelConfigSchema", { enumerable: true, get: function () { return types_js_1.ChannelConfigSchema; } });
Object.defineProperty(exports, "ChannelsConfigSchema", { enumerable: true, get: function () { return types_js_1.ChannelsConfigSchema; } });
Object.defineProperty(exports, "ValidationResultSchema", { enumerable: true, get: function () { return types_js_1.ValidationResultSchema; } });
Object.defineProperty(exports, "ConnectionTestResultSchema", { enumerable: true, get: function () { return types_js_1.ConnectionTestResultSchema; } });
Object.defineProperty(exports, "ChannelError", { enumerable: true, get: function () { return types_js_1.ChannelError; } });
Object.defineProperty(exports, "ChannelNotFoundError", { enumerable: true, get: function () { return types_js_1.ChannelNotFoundError; } });
Object.defineProperty(exports, "ChannelValidationError", { enumerable: true, get: function () { return types_js_1.ChannelValidationError; } });
Object.defineProperty(exports, "ChannelAlreadyExistsError", { enumerable: true, get: function () { return types_js_1.ChannelAlreadyExistsError; } });
Object.defineProperty(exports, "CURRENT_VERSION", { enumerable: true, get: function () { return types_js_1.CURRENT_VERSION; } });
var validation_js_1 = require("./validation.js");
Object.defineProperty(exports, "validateChannelConfig", { enumerable: true, get: function () { return validation_js_1.validateChannelConfig; } });
Object.defineProperty(exports, "assertValidChannelConfig", { enumerable: true, get: function () { return validation_js_1.assertValidChannelConfig; } });
Object.defineProperty(exports, "isValidChannelId", { enumerable: true, get: function () { return validation_js_1.isValidChannelId; } });
Object.defineProperty(exports, "isValidChannelType", { enumerable: true, get: function () { return validation_js_1.isValidChannelType; } });
Object.defineProperty(exports, "matchesFilterPatterns", { enumerable: true, get: function () { return validation_js_1.matchesFilterPatterns; } });
Object.defineProperty(exports, "isUserAllowed", { enumerable: true, get: function () { return validation_js_1.isUserAllowed; } });
var registry_js_1 = require("./registry.js");
Object.defineProperty(exports, "ChannelRegistry", { enumerable: true, get: function () { return registry_js_1.ChannelRegistry; } });
Object.defineProperty(exports, "createRegistry", { enumerable: true, get: function () { return registry_js_1.createRegistry; } });
var storage_js_1 = require("./storage.js");
Object.defineProperty(exports, "ChannelStorage", { enumerable: true, get: function () { return storage_js_1.ChannelStorage; } });
Object.defineProperty(exports, "createStorage", { enumerable: true, get: function () { return storage_js_1.createStorage; } });
